### ISSUE TITLE
Bad url for organization repos?

### ISSUE THREAD

**Issue by boturnbow** [MeetHyde/MeetHyde#1]
Thanks for the app - great idea! I would like to try it out, but all the GH pages repos that I work with are under organizations rather than my personal account. After configuring a token I can start Meet Hyde up and see the repos from my organizations, however when I click on one I get your pulsing spinner and the next view never loads. Firefox and Chrome on Ubuntu.

The console shows a couple of 404s for URLs like: https://api.github.com/repos/boturnbow/helenaciviccenterboard.github.io/git/trees/gh-pages?&1447189636341 I believe the problem is that my username "boturnbow" is in the url rather than the organization's name.

**Comment by MeetHyde** [comment]
Hi boturnbow, just test it out and you're right thanks for pointing it out, I'm already solving it, let you know when it's done.

**Comment by MeetHyde** [comment]
Hi, the bug have been fixed and the files have been updated in the release, you can go ahead and download it.

**Comment by boturnbow** [comment]
Thanks for the fix! I finally tested and it worked for me.
