### ISSUE TITLE
Can't detect my github.io repo

### ISSUE THREAD

**Issue by lee-dohm** [MeetHyde/MeetHyde#4]
I have a public repo lee-dohm/lee-dohm.github.io that, according to the error message, is of the format that Meet Hyde is supposed to be able to handle. I've granted private repo, gist and user scopes to the token I generated for the app. Is there some other scope that it requires?

<img width="1284" alt="screen shot 2015-11-18 at 3 17 26 pm" src="https://cloud.githubusercontent.com/assets/1038121/11257608/819fa800-8e07-11e5-84ed-c5c60048282a.png">

**Comment by MeetHyde** [comment]
That's weird, I just tried it with my own repo and the following options: 

```
repo, gist, user 
```

and next with:

```
public_repo, gist, user 
```

and it worked.

To display the repos the app uses the repositories API which can be publicly accessed through
```
https://api.github.com/users/username/repos
```

and only access repos which return "true" to the "has_pages" value.

In fact if I replace "username" by your username "lee-dohm" in the previous code snippet and access it through the browser, I can see that 3 of your repos return "true" for "has_pages" so 3 repos should be shown by the app.

Did you download the latest release? If so please remove the access token and generate a new one. Just to test grant all privileges and let me know

**Comment by lee-dohm** [comment]
I downloaded it just today, v0.1.1. I generated a new token with all scopes granted and it gave me the same error. Could it be due to the fact that I have over 100 repositories? Is it asking for a sort order or something that puts the repos that have pages after the first 30 that get returned?

**Comment by MeetHyde** [comment]
Hi, I think the error may be in the way the API call is made, I just made a change to it which I think should solve your problem, please try opening the app again and let me know if it's working

**Comment by lee-dohm** [comment]
That worked, partially. I now get some results:

<img width="578" alt="screen shot 2015-11-19 at 10 00 06 am" src="https://cloud.githubusercontent.com/assets/1038121/11279270/57ab56dc-8ea4-11e5-9051-13b0fcc7850a.png">

But the one I really want to edit is lee-dohm/lee-dohm.github.io and it isn't showing up in the list.

**Comment by MeetHyde** [comment]
Right, really sorry about that I just missed the pagination.... I'm pretty sure it should work as expected now

**Comment by lee-dohm** [comment]
I'm still not getting the lee-dohm/lee-dohm.github.io repo in the list, though many more are showing up. Could it be that it uses a main branch that is called `source` instead of `master`?

<img width="1248" alt="screen shot 2015-11-19 at 5 14 03 pm" src="https://cloud.githubusercontent.com/assets/1038121/11289381/218181ac-8ee1-11e5-97d0-0b9674126fb3.png">

**Comment by MeetHyde** [comment]
In fact the app tracks the master branch, originally I didn't think on the scenario where the site could be in a different branch but this can be easily fixed with an option to select the branch the user would like to work on.

Nevertheless the main problem is in the pagination, I can't replicate the exact behavior you're getting since the API call used in the app needs authentication, I did try with a different API call which is public and it did return the lee-dohm/lee-dohm.github.io repo but this API can't be used in the app because it doesn't return organizations repos or any other repo the user collaborates to. 

Let me do some trials as I already saw the problem is with the pagination and let you know when I come with a solution

**Comment by lee-dohm** [comment]
Sounds good, sorry to be a constant thorn in your side :grinning:

**Comment by MeetHyde** [comment]
Don't worry Lee, you're helping me to fix bugs and make the app better... I already try it out with the public API call I mentioned before and it's working fine so it should work the same for the authenticated API, please try again and let me know, it should now show all your websites

**Comment by lee-dohm** [comment]
Yes, it works now. Thanks!
